### ISSUE TITLE
Wizard should constantly check internet connection

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#2700]
There's the possibility of losing the internet after the internet step, so we probably should go back to that step if the connection fails.

_Originally posted by @joaoantoniocardoso in https://github.com/bluerobotics/BlueOS/issues/1830#issuecomment-1611394693_
            

https://user-images.githubusercontent.com/5920286/340807954-6ff1a1e8-990b-4e31-bc69-ee0a61b304e3.mp4

 BlueOS Version: tags/1.3.0-beta.5-0-geb70c041

**Comment by patrickelectric** [comment]
@joaoantoniocardoso the video does not exist.

**Comment by patrickelectric** [comment]
@JoaoMario109 can you confirm that this is still an issue ? As you said, this appears to be fixed already in master (#2584 ?)

**Comment by joaoantoniocardoso** [comment]
> @joaoantoniocardoso the video does not exist.

fixed

**Comment by patrickelectric** [comment]
@joaoantoniocardoso fix is already fixed in master, right ?

**Comment by joaoantoniocardoso** [comment]
Still the same problem:

https://github.com/bluerobotics/BlueOS/assets/5920286/fcfa7a1f-6e2b-4c5b-a113-410670791563

**Comment by patrickelectric** [comment]
@JoaoMario109 can you take a look ?
